FriendsOfREDAXO/tricks

howto_ajax_rexapi.md
die() und exit() sind Äquivalent. Da hier beides im gleichen code gemischt wurde wirkt es wie unterschiedliche dinge..
=> Einheitlich exit() verwenden

addons_development.md, snippet_helper_functions.md
Addon Entwicklung wird evtl jetzt schon in der Doku behandelt. 
Helper Functions ist neu aus Infos aus dem Slack-channel zusammengestellt.
=> snippet_helper_functions

theme_debug_module.md
Ein kleiner Trick für das Theme AddOn, den ich mal festhalten wollte. Nach einem Gespräch mit @marcohanke als Funktion ins Backend eingebunden.
=> Add theme_debug_module.md

theme_language_switch.md
Ein einfacher Weg um per Theme AddOn einen Language Switch im Frontend auszugeben.
=> Add theme_language_switch.md

addons_yrewrite_nginx.md
da jetzt ein /bin Verzeichnis dazu gekommen ist
=> anpassungen für redaxo 5.4

README.md, redaxo-argumentationshilfe.md
In dem Dokument geht es darum, wie REDAXO an den Kunden gebracht werden kann. Wiederkehrende Fragen von Kunden, die REDAXO noch nicht kennen, werden behandelt.
Ich habe das Dokument nur aus chronologischer Sicht ganz vorne verlinkt.
=> Argumentationshilfe

addons_yform_im-addon.md
Kleinere Fehler behoben, neuer Beispielcode in zwei Versionen (simpel und Luxus), Text entsprechend redigiert
=> Neuer Beispielcode in zwei Versionen (simpel/Luxus), Text angepasst

addons_project_class_pagination.md
Die nächste/letzte Seite wurde nicht korrekt berechnet. Hier muss aufgerundet statt abgerundet werden.
=> Berechnung nächste/letzte Seite angepasst

_docs/addons/yform/snippets.md
Kurze, aber vielleicht nützliche Ergänzung, irgendwo mal aus einem Issue gezogen ;)
=> Choice Felder auslesen

_docs/addons/yform/own_submit_button_php.md
/cc @danspringer einverstanden? Würde das so auch in die YForm-Doku übernehmen.
=> Korrekturen, bad practice durch best practice ersetzt.

_docs/howto/rex_sql_sync.md
Wie man Datensätze aus externen Quellen aktualisiert
=> Daten mit rex_sql synchronisieren

_docs/addons/yform/update_dataset
Möglicherweise auch für Andere hilfreich, einen einfacheren Weg habe ich bis jetzt nicht gefunden :)
=> YForm Tablemanager: Mit aktuellem Datensatz andere Tabellen bearbeiten

_includes/head.html
=> Zugriff Verifizierung Google Search Console

_docs/howto/sicherheitstipps.md
Hallo zusammen, 
ich habe mich mal dem Thema Sicherheitstipps angenommen, bitte um Feedback;
Thema HSTS bei unterschiedlichen Providern wird in Kürze ergänzt. 
close #30 #60
=> Sicherheitstipps

_docs/addons/yform/xlsx_import, _docs/howto/errorcode_410.md
Hi, daran dass es drei commits sind sieht man, dass ich mich da gerade noch reinfuchse. Bitte genau draufschauen und bitte rückmelden ob das so richtig ist :-)
=> XLSX Export aus YForm

_docs/howto/redaxo_ddev.md
Ein paar kleine Rechtschreibkorrekturen und sonstige Anpassungen. Schau mal, ob es dir so passt, @crydotsnake.
=> DDEV: Kleine Korrekturen

_docs/addons/sked/config.md, _docs/addons/ycom/protected_files_enhanced.md, _docs/addons/yform/copy_dataset.md, _docs/addons/yform/im-addon.md, _docs/addons/yform/protect_in_use_data.md
Textverbesserungen, sowie code mit jeweiliger sprache angepasst.
=> Textverbesserungen

_data/navigation.yml, _docs/development/editor-vscode.md
Neuer Menüpunkt "Development" und neuer Trick editor-vscode.md
=> Editor-Einstellungen VSCode

_docs/development/editor-vscode.md
Reverts FriendsOfREDAXO/tricks#214
=> Revert "Anpassungen & Verbesserungen"

_docs/development/editor-vscode.md
=> Überschrift angepasst

_docs/development/editor-vscode.md
Kleinere Textanpassungen und mit markdownlint überarbeitet
=> Markdown überarbeitet

_docs/backend/backend_snippets.md
Warte noch auf den Autor-Github-Account zwecks Verlinkung
=> Tricks aus Slack zu Backend-Seiten ausblenden

_docs/addons/yform/im-addon.md
- für YForm ab V3.4: Titel per EP ausblenden
- neue Struktur der Properties in *package.yml*
- Text und Musterscript komplett neu
=> V2.0: runderneuert

_docs/addons/yrewrite/yrewrite_sitemap.md
Beispiel für EP YREWRITE_DOMAIN_SITEMAP
=> yrewrite - sitemap.xml um zusätzliche Seiten erweitern

_docs/backend/rex_list_row_marker.md
closes https://github.com/yakamara/redaxo_yform_docs/issues/138 
via @christophboecker
=> Update rex_list_row_marker.md YFORM_DATA_LIST_SQL

_docs/development/adminDump.md
=> add adminDump.md

_docs/module/einfacher_repeater.md
Repeater: Beispiel für ein Bildfeld hinzugefügt...
=> REX_MEDIA hinzugefügt

_docs/backend/be_navi_order.md
=> Ergänzungen zu Eintragungen im Backend-Menü

_docs/snippets/new_category_priority.md
Neue Kategorien beim erstellen mit Prio 1 anlegen
=> Snippet: Neue Kategorien mit Prio 1 anlegen

_docs/addons/geolocation/add_infobox.md
Bei der letzten Überarbeitung vergessen :-(
=> Namespace korrigiert

_config.yml
=> config: update markdown settings to use GFM

_docs/development/editor-vscode.md
VSCode 1.75.0
Die HTMLHint Version von Mike Kaufman wird als depricated angezeigt.
=> HTMLHint neue Version

_docs/development/editor-vscode.md
Ein Hinweis auf das Issue ... bis der Artikel überbearbeitet ist.
Etwas besseres viel mir grad nicht ein, um Besucher nicht gänzlich als Fragezeichen vor dem Bildschirm sitzen zu lassen.
=> Hinweis auf Issue ... Baustelle

_docs/addons/yform/snippets.md
YFORM_DATA_LIST_QUERY statt YFORM_DATA_LIST_SQL
zudem leicht überarbeitet und gekürzt
=> update snippets.md change yform data list order by

_docs/addons/yform/snippets.md
Table Manager: Extensionpoint | Listensortierung beeinflussen text was outdated
=> update outdated description

_docs/development/editor-vscode.md
NEU: Microsoft Edge Tools, axe Accessibility Linter und Web Accessibility.
=> Update VSCode - Erweiterungen für Barrierefreiheit ergänzt

_docs/addons/geolocation/add_infobox.md
Nummerierte Marker-Liste mit Popup-Text
=> neues Beispieltool NrMarkerPlus

_docs/addons/yform/multistep-form.md
=> YForm: Mehrstufige Formulare (Steps, Wizard, ...)

_docs/development/editor-vscode.md
Schritt 5 korrigiert und Erklärung zu Einstellungen etwas erweitert (es war nicht klar, wo die Datei php-cs-fixer.phar herkommt)
=> Schritt 5 korrigiert

_docs/module/rss-feed.md
=> Skerbis patch rss

_sass/_algolia.scss, assets/css/style.scss
Ändert die reguläre Algolia-Suche Farbe auf das FOR-Blau.
=> Algolia styles

_docs/development/namespace_a.md
Diese Beschreibung richtet sich insbesondere an diejenigen, die bisher noch keine
Erfahrungen mit Namespaces haben bzw. mit PHP nicht ganz so sattelfest sind.
Es geht um die nötigen Anpassungen im eigenen System, wenn ein benutztes Addon
auf Namespace umgestellt wurde:
- Muss ich etwas tun?
- Wo können Anpassungen notwendig sein (nicht nur im Code selbst ...)
- Wie finde ich die Stellen
- Was muss ich wie ändern
Ohne Anspruch auf Vollständigkeit. Bitter gerne ergänzen und Korrigieren
=> Oh! Das Addon hat "Namespace"! Und nun?

_docs/development/laragon.md
Einrichtung einer kleinen lokalen Entwicklungsumgebung in Windows mit Anpassungen an REDAXO (SSL, Cronjob).
=> Laragon-Tutorial

_docs/addons/consent_manager/google_consent_mode_v2.md
4.3.0 wurde am  11.04.2024. Der Hinweis auf eine ausstehende Veröffentlichung wurde entfernt.
=> Hinweis Veröffentlichung entfernt
